INSERT INTO STUDENT(STUDENT_NAME, AVERAGE_SCORE, CLASS_RANK) VALUES('XXX', 66, 10);
INSERT INTO STUDENT(STUDENT_NAME, AVERAGE_SCORE, CLASS_RANK) VALUES('XXY', 76, 9);
INSERT INTO STUDENT(STUDENT_NAME, AVERAGE_SCORE, CLASS_RANK) VALUES('XXZ', 86, 8);
INSERT INTO STUDENT(STUDENT_NAME, AVERAGE_SCORE, CLASS_RANK) VALUES('XYZ', 87, 7);
INSERT INTO STUDENT(STUDENT_NAME, AVERAGE_SCORE, CLASS_RANK) VALUES('XZY', 90, 6);